
1. Как в данной функции вызвать исключения?

  const calculateTotal = (order) => {
    
  };